api_key: AIzaSyD2p3GTSPSP18PxYCp1RpeQy4VynaGSVaE
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns: []
