name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 使用旧版本，需要升级
      
    - name: Setup Node.js
      uses: actions/setup-node@v3  # 使用旧版本，需要升级
      with:
        node-version: '18'
        # 缺少缓存配置
        
    - name: Install dependencies
      run: npm ci  # 没有缓存，每次都会重新安装
      
    - name: Run tests
      run: npm test
      
    - name: Run linting
      run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: test  # 串行执行，可以优化为并行
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/
        retention-days: 30  # 保留时间过长

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # 部署脚本
