name: Translate Documentation
on:
  push:
    branches: [ main, master ]
    paths: [ 'docs/**' ]
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Translate to Traditional Chinese
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-TW
